### ISSUE TITLE
Use unique view IDs

### ISSUE THREAD

**Issue by josh-burton** [leinardi/FloatingActionButtonSpeedDial#100]
It would be a good idea to prefix view ids used in the library to make them unique.

I'm getting the following error:

```
Wrong state class, expecting View State but received class com.google.android.material.stateful.ExtendableSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/fab.
```

It turns out this is because this library uses a `id/fab`, and I use `id/fab` for the SpeedDial view. 

I imagine its quite common for developers to use the `id/fab` id, so prefixing yours would help avoid this erorr.

**Comment by leinardi** [comment]
Very good point, thanks for reporting this issue.

**Comment by leinardi** [comment]
Released fix: https://github.com/leinardi/FloatingActionButtonSpeedDial/releases/tag/3.0.0
