### ISSUE TITLE
How to Disable Main Fab programmatically

### ISSUE THREAD

**Issue by francescogatto** [leinardi/FloatingActionButtonSpeedDial#101]
Hi, 
I'm trying to disable the main fab to prevent to open the menu. I tried with  enabled and clickable, but it doesn't work

**Comment by leinardi** [comment]
Ciao @francescogatto, thanks for reporting this issue. I'm planning to fix it for the next release but meanwhile you can work around it using `setEnabled()` directly on the main FAB: `mSpeedDialView.getMainFab().setEnabled(false);`
