### ISSUE TITLE
Info about checked in .idea files

### ISSUE THREAD

**Issue by hannesa2** [leinardi/FloatingActionButtonSpeedDial#102]
Just for your info

1)
when I open the repo with Android Studio 3.2.1 the checked in .idea files are modified immediate

<img width="606" alt="image" src="https://user-images.githubusercontent.com/3314607/49423420-c4e0f680-f797-11e8-9384-029281035fca.png">

I'm not sure if this is the main purpose of this checked in files. I guess it needs an update

2)
Android Studio asked me about to update project build tools and because of the over engineered project setup, it failed

**Comment by leinardi** [comment]
Hi Hannes, yes, like in the DSA PAYBACK project, those files are modified immediately. I am not aware of any fix for it.
