### ISSUE TITLE
How to get click status of a sub menu

### ISSUE THREAD

**Issue by waseem786** [leinardi/FloatingActionButtonSpeedDial#105]
Hi, what I am looking is, when I click a sub menu, its background color need to change, and when click same sub menu item again, its color need to change back to previous color. Is there any function or boolean value to do this? 
Note: I am not talking about subMenuItem.isLabelClickable method.

Thanks

**Comment by leinardi** [comment]
Currently there is no support for toggle status of an action item. If you need something like that you have to handle the logic yourself replacing an action item when clicked with another that uses a different color.
