### ISSUE TITLE
Action Items are sometimes not visible or not drawn correctly

### ISSUE THREAD

**Issue by sauravrp** [leinardi/FloatingActionButtonSpeedDial#106]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `2.0.1`
 - Android version: `8.1.0`
 - Support library version: `?`
 - Device brand: `Android Emulator`
 - Device model: `Android Emulator`

#### Steps to reproduce:

 When dynamically adding/removing action items, sometimes the user will fail to see the speed dial action items. This seems to occur more when the user is switching in and out of the app or doing some operations outside of the app such as enabling/disabling airplane mode.
![filterbug](https://user-images.githubusercontent.com/3660385/50248398-830f9d00-03a0-11e9-9774-06579e9d6d72.gif)

#### Observed Results:

  * 
  

#### Expected Results:

  * 

#### Relevant Code:

```java
System.out.println("Hello, world!");
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at jahirfiquitiva.libs.fabsmenu.HelloWorld
    at jahirfiquitiva.libs.fabsmenu.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

**Comment by leinardi** [comment]
Hey, sorry for the 3 months wait. It looks like the SpeedDial has no space to expand freely. Can you try to ensure that the view is free to grow if needed?

If you can post the XML layout where the view is added.
