### ISSUE TITLE
Add action FAB size option

### ISSUE THREAD

**Issue by leinardi** [leinardi/FloatingActionButtonSpeedDial#11]
Allow to use size normal for the Speed Dial action items

**Comment by leinardi** [comment]
Blocked by https://issuetracker.google.com/issues/77303906

(please star the issue to make it more visible)

**Comment by urgentx** [comment]
Custom sizing would make the button much more versatile. Currently, half of the FAB is not drawn when using a custom width/height in XML, as such it makes it unusable for anything other than its default size.

**Comment by francescogatto** [comment]
https://issuetracker.google.com/issues/77303906 they say that finally fixed this bug! 💃

**Comment by leinardi** [comment]
And that "it will be available in future" :(

**Comment by francescogatto** [comment]
I have a question, I need to change the size, so if i fork the library and change to AndroidX, can I resize the Fab button? Thx

**Comment by leinardi** [comment]
I don't think the fix is already released but if you try and it works, please let me know.

**Comment by untungs** [comment]
Hi @leinardi, I've tried with `com.google.android.material:material:1.1.0-alpha02` and the issue doesn't occur.

XML
```
<com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_marginEnd="@dimen/fab_margin"
        android:layout_marginBottom="@dimen/fab_margin"
        android:src="@drawable/ic_android" />
```

Kotlin
```
fab.setOnClickListener {
    fab.size = if (fab.size != SIZE_MINI) SIZE_MINI else SIZE_NORMAL
}
```

**Comment by codefury** [comment]
Hey @leinardi, are you working on this?

**Comment by leinardi** [comment]
hey, sorry but I don't have much time lately...

**Comment by alexamenos** [comment]
Is there any news about it @leinardi ?

**Comment by leinardi** [comment]
I have re-enabled the `setFabSize()` method, it seems to work fine (API 16 and 27):
![image](https://user-images.githubusercontent.com/273338/66254003-837ef600-e770-11e9-8f40-cb022a59eff2.png) ![image](https://user-images.githubusercontent.com/273338/66254029-f12b2200-e770-11e9-8055-66df71ff661c.png)
