### ISSUE TITLE
Update Label

### ISSUE THREAD

**Issue by ulaserdegor** [leinardi/FloatingActionButtonSpeedDial#110]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `?`
 - Android version: `?`
 - Support library version: `?`
 - Device brand: `?`
 - Device model: `?`

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * 
  

#### Expected Results:

  * 

#### Relevant Code:

```java
System.out.println("Hello, world!");
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at jahirfiquitiva.libs.fabsmenu.HelloWorld
    at jahirfiquitiva.libs.fabsmenu.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

**Comment by ulaserdegor** [comment]
Can you add setLabel method for items ?

**Comment by leinardi** [comment]
If you want to update a label you should use the `getSpeedDialActionItemBuilder()':

https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java#L69
