### ISSUE TITLE
Main FAB opened image is not centered when using Theme.MaterialComponents

### ISSUE THREAD

**Issue by primozi** [leinardi/FloatingActionButtonSpeedDial#113]

**Comment by primozi** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c79c501d10f9e0011d010f7/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a2282886b07bbe1122525e0a48ac41590d46aaac812eaea42062c80d55b98e30063e937f03a6aa8317b500bf258a4b8db2b88f45c0ee3937aa.PNG)

**Comment by leinardi** [comment]
I've updated the Sample app so that now uses the Material Component theme but I can't reproduce the issue. Can you please try to reproduce it with the sample app?

**Comment by PkmX** [comment]
I also got the same problem when I upgraded `com.google.android.material:material` from `1.0.0` to `1.1.0-alpha04`.

**Comment by primozi** [comment]
Did it, but it works (same device/emulator).
Maybe there's a problem with androidx that I use in my app, but you do not?
Didn't try to change sample app to androidx because I have no idea how to do it except manually

**Comment by primozi** [comment]
> I also got the same problem when I upgraded `com.google.android.material:material` from `1.0.0` to `1.1.0-alpha04`.

@PkmX is right.
1.1.0-alpha04 is the culprit. Downgrade to 1.0.0 solved the issue.

**Comment by devjn** [comment]
Any update? Still reproducible with latest `com.google.android.material:material` `1.1.0-alpha09`

**Comment by roiacult** [comment]
I'm facing same problem and i can't downgrade matrial library 
Please any update

**Comment by roiacult** [comment]
i solved this problem  by setting the drawable image programaticlly every time toggle change like this 
`
binding.editButton.setOnChangeListener(object : SpeedDialView.OnChangeListener{

            override fun onMainActionSelected() = false

            override fun onToggleChanged(isOpen: Boolean) {

                binding.editButton.mainFab.setImageDrawable(
                    ContextCompat.getDrawable(context!!,R.drawable.plus )
                )

            }
            
        })
`

**Comment by leinardi** [comment]
The issue seems related to the `UiUtils.getRotateDrawable()` method, specifically, when using version 1.1.x of Material Components, the `rawable.getBounds()` returns 0 as width and height.
https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/dc7396d62f134dd4044f1ce0123af4dad0fcb45a/library/src/main/java/com/leinardi/android/speeddial/UiUtils.java#L236
Currently I have no idea on how to fix/workaround this issue. Suggestions are welcome.

@roiacult I guess your solution only works with the plus icon and a rotation angle multiple of 90°, because the plus is symmetrical on both X and Y axes.

**Comment by icvetkovic** [comment]
@leinardi have you tried using `getIntrinsicWidth()` and `getIntrinsicHeight()` with fallback to `getBounds()` in case one of these returns -1?

I've stumbled upon same issue on Material Components 1.1.0-alpha09 and quick cloning and changing of the line you marked in your comment fixed the issue in the example app, as shown in the gif below.

[GIF](https://i.imgur.com/c3H1beX.gifv)

**Comment by leinardi** [comment]
Hey @icvetkovic thanks! That actually fixes the issue :+1:

**Comment by icvetkovic** [comment]
No problem @leinardi, my pleasure :)
