### ISSUE TITLE
How to remove the white layer of the background?

### ISSUE THREAD

**Issue by RockyQu** [leinardi/FloatingActionButtonSpeedDial#114]
How to remove the white layer of the background?

**Comment by leinardi** [comment]
If by "white layer of the background" you mean, the overlay, the easiest way is to not add it in first place:
just remove the attribute `app:sdOverlayLayout="@id/overlay"` from the `com.leinardi.android.speeddial.SpeedDialView` in your layout and remove also this:
```
<com.leinardi.android.speeddial.SpeedDialOverlayLayout
        android:id="@+id/overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:clickable_overlay="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />
```

If instead you refer to the action item background, you can just call `.setLabelBackgroundColor(Color.TRANSPARENT)` when you build it (check the sample app).

**Comment by RockyQu** [comment]
Sorry, maybe I didn’t express it clearly.
This means that when the menu is opened, the entire background will become translucent white. How to remove it?

**Comment by RockyQu** [comment]
Thank you, I just finished.
