### ISSUE TITLE
How to hide fab on clicking anywhere in the screen

### ISSUE THREAD

**Issue by ejChathuranga** [leinardi/FloatingActionButtonSpeedDial#120]
How to hide fab on clicking anywhere in the screen?

**Comment by leinardi** [comment]
That's the default behavior if you add an overlay. You can check the sample if you want to see an example.

**Comment by ejChathuranga** [comment]
`<com.leinardi.android.speeddial.SpeedDialOverlayLayout
        android:id="@+id/overlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:clickable_overlay="true"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>`


`    <com.leinardi.android.speeddial.SpeedDialView
        android:id="@+id/speedDial"
      ...
        app:sdMainFabOpenedSrc="@drawable/ic_settings" />`
