### ISSUE TITLE
setFabImageTintColor() not working?

### ISSUE THREAD

**Issue by bagintz** [leinardi/FloatingActionButtonSpeedDial#124]
I am setting up my speed dial action items by adding them in a fragment.  No matter what I do, the setFabImageTintColor() does not change the icon/image color.  I am not even sure where to start troubleshooting, any ideas?

The only thing I was able to ascertain is that the value of the color after being set is -1

Thanks,
Bryan

**Comment by bagintz** [comment]
Any thoughts on this?

**Comment by liltof** [comment]
Same problem here... Any clue ?

**Comment by liltof** [comment]
@bagintz 
Ok I found a workaround : 
It seems that the tinting feature on action items is not called when you add an item, but is called when you set it later. This workaround also seems to work **only** when you use the `SpeedDialActionItem.Builder(int, Drawable)` method (not the `SpeedDialActionItem.Builder(int, int)` one. So you need to call `setSpeedDialActionItem` **after** adding the item

Here is the code
```
      Drawable drawable = AppCompatResources.getDrawable(this, R.drawable.myicon);
        FabWithLabelView fabWithLabelView = mBinding.speedDial.addActionItem(new SpeedDialActionItem.Builder(R.id
                .btnAddEvent, drawable)
                .setLabel(R.string.mytext)
                .setFabBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.white,
                        getTheme()))
                .setLabelColor(ResourcesCompat.getColor(getResources(), R.color.black, getTheme()))
                .setLabelBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.white,
                        getTheme()))
                .setFabImageTintColor(ResourcesCompat.getColor(getResources(), R.color.red,
                        getTheme()))
                .create());
        if (fabWithLabelView != null) {
            fabWithLabelView.setSpeedDialActionItem(fabWithLabelView.getSpeedDialActionItemBuilder()
                    .create());
        }
```

**Comment by zhanghai** [comment]
#127 might be a fix for this issue, and I would appreciate it if someone on this thread can test it. I encountered a similar problem and submitted that fix.

**Comment by leinardi** [comment]
@zhanghai I merged your PR.

@bagintz @liltof can you please try to modify the sample project to reproduce the issue? I don't understand how to reproduce it...
