### ISSUE TITLE
Open fab doesnt show correctly when label is set

### ISSUE THREAD

**Issue by emmanuel0027** [leinardi/FloatingActionButtonSpeedDial#128]
This is a awesome library but I have a problem when fab is opened and label is set with any text, the fab moves to right side and only show middle fab and action item, when I dont set a label this work correctly

Fab open:
https://imgur.com/a/1GUVv9B

Fab close:
https://imgur.com/a/tRssq9v

**Comment by leinardi** [comment]
Can you please post the XML of the layout where you are adding the `com.leinardi.android.speeddial.SpeedDialView`?

**Comment by emmanuel0027** [comment]
Java:

>  SpeedDialView speedDialView = findViewById(R.id.speedDial);
        speedDialView.addActionItem(
                new SpeedDialActionItem.Builder(R.id.fab_no_label, R.drawable.ic_bus_black)
                        .setFabImageTintColor(ResourcesCompat.getColor(getResources(), R.color.white, getTheme()))
                        .setLabel("Sentidoida")
                        .setFabBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.white, getTheme()))
                        .setLabelColor(ResourcesCompat.getColor(getResources(), R.color.black, getTheme()))
                        .create()
        );


XML:

> <com.leinardi.android.speeddial.SpeedDialOverlayLayout
			android:id="@+id/overlay"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			app:clickable_overlay="true"
			app:layout_behavior="@string/appbar_scrolling_view_behavior" />

> <com.leinardi.android.speeddial.SpeedDialView
			android:id="@+id/speedDial"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_marginEnd="15dp"
			android:layout_marginBottom="16dp"
			app:layout_behavior="@string/speeddial_scrolling_view_snackbar_behavior"
			app:sdExpansionMode="top"
			app:sdMainFabAnimationRotateAngle="90"
			app:sdMainFabClosedSrc="@drawable/ic_bus_black"
			app:sdMainFabOpenedSrc="@drawable/ic_bus_white"
			app:sdOverlayLayout="@id/overlay"
			map:layout_constraintBottom_toTopOf="@+id/gpsbutton"
			map:layout_constraintEnd_toEndOf="parent"
			map:layout_constraintStart_toStartOf="@+id/gpsbutton"
			map:sdMainFabClosedBackgroundColor="@color/white"
			map:sdMainFabOpenedBackgroundColor="@color/black" />

**Comment by leinardi** [comment]
I would guess that the issue is related to this: `map:layout_constraintStart_toStartOf="@+id/gpsbutton"` but can't be sure without the entire layout, parent included.

**Comment by emmanuel0027** [comment]
Yes that was the problem! Sorry and thank u!
