### ISSUE TITLE
how can I close FAB when touch outside?

### ISSUE THREAD

**Issue by haxuansang** [leinardi/FloatingActionButtonSpeedDial#135]
I wanna close FAB when I touch outside that.

**Comment by DatL4g** [comment]
You could set a TouchListener on the root view and close it dynamically

**Comment by leinardi** [comment]
Just use the [SpeedDialOverlayLayout](https://github.com/leinardi/FloatingActionButtonSpeedDial#adding-an-overlaytouch-guard-when-the-menu-is-open-like-inbox-by-gmail) and set the color to transparent.
