### ISSUE TITLE
Place label on the right side (end) of the floating action button

### ISSUE THREAD

**Issue by chayanforyou** [leinardi/FloatingActionButtonSpeedDial#142]
Please let me know is there any way to place the label on the right side (end) of the floating action menu button?

**Comment by john990** [comment]
I haven't found the relevant ending method, and I have created an issue (https://github.com/leinardi/FloatingActionButtonSpeedDial/issues/143), but I haven't got a reply. Have you found a solution? It seems that it can only be achieved by itself.

**Comment by chayanforyou** [comment]
Yes, there is no method for it. I got it by modifying myself.

**Comment by kabumere** [comment]
@chayanforyou @john990 If you still need this functionality, the [ExpandableFab](https://github.com/nambicompany/expandable-fab) library allows you to do this out of the box.
