### ISSUE TITLE
Add Support for drawable in SpeedDialActionItem#Builder

### ISSUE THREAD

**Issue by emansih** [leinardi/FloatingActionButtonSpeedDial#15]
I was wondering if you could add support for drawable for SpeedDialActionItem#Builder? Currently it takes in int, int as an argument. Would be nice if it takes in int,drawable as an argument too.

**Comment by emansih** [comment]
Use case: 

`
 speedDialView.addAllFabOptionItem(
                new SpeedDialActionItem.Builder("Mail",
                        new IconicsDrawable(requireContext())
                .icon(GoogleMaterial.Icon.gmd_mail))
                .create());
`

**Comment by leinardi** [comment]
Hi @emansih, I had already this idea but I have not implemented it yet. I will do for sure soon :+1: .

**Comment by leinardi** [comment]
Hi @emansih, I made a PR that implement the new constructor. If you have time please have a look.

**Comment by emansih** [comment]
Just got back and tested it. Thanks!
