### ISSUE TITLE
From Where do you get the id of a floating action label id?

### ISSUE THREAD

**Issue by aminPial** [leinardi/FloatingActionButtonSpeedDial#150]
```
SpeedDialActionItem.Builder(R.id.fab_no_label, R.drawable
                    .ic_link_white_24dp)
```
from where you get `R.id.fab_no_label`, can't really understand!:( Sorry for this dumb question.

**Comment by leinardi** [comment]
Hi @aminPial, those ids are declared here: https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/release/sample/src/main/res/values/ids.xml

You can do the same on your project, just declare them like this inside your resources' values: `<item name="fab_no_label" type="id" />`.
