### ISSUE TITLE
SpeedDial is moving when it's pressed

### ISSUE THREAD

**Issue by LuX1nAt0r** [leinardi/FloatingActionButtonSpeedDial#157]
So I tried to implement the speeddial into my layout witch is a coordinator layout. I have a bottomappbar and I want to have the fab in the bottom middle but when I press the fab and the speeddialer expends it moves like a hundret dp to the right. Is there an easy way to fix this issue?

**Comment by FaridBen95** [comment]
@LuX1nAt0r did you find any solution for this issue ??
