### ISSUE TITLE
Publish latest version to Maven Central, now that JCenter will be sunset

### ISSUE THREAD

**Issue by VincentJoshuaET** [leinardi/FloatingActionButtonSpeedDial#159]

**Comment by VincentJoshuaET** [comment]
Looks like 3.1.1 is available on Jitpack:

`implementation 'com.github.leinardi:FloatingActionButtonSpeedDial:3.1.1'`

**Comment by jackmichalak** [comment]
Can the maintainers confirm whether they'll be migrating to Maven Central? (For the most recent version at least?) Not sure why I'd have any more confidence in JitPack staying around than JCenter.

**Comment by leinardi** [comment]
I would like to but I never published anything on Maven Central and it seems to be way more complex (at least for me) than publishing something on Bintray: https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

@jahirfiquitiva would you be able to provide support for this?

**Comment by jahirfiquitiva** [comment]
@leinardi count on me, although this might take me a few days, I'm quite busy lately ... also, do you have somewhere we can talk privately to share the generated keys, secrets and stuff?

**Comment by leinardi** [comment]
OK, I think I'm very close:
![image](https://user-images.githubusercontent.com/273338/119224432-b705c400-bafe-11eb-9b6d-0b555cf6d533.png)

**Comment by jahirfiquitiva** [comment]
@leinardi yes you are... just close, refresh, release 😄

**Comment by leinardi** [comment]
Release 3.2.0 is available on Maven Central: https://repo1.maven.org/maven2/com/leinardi/android/speed-dial/maven-metadata.xml
