### ISSUE TITLE
New Release, e.g. version 3.2.0?

### ISSUE THREAD

**Issue by fabiankr** [leinardi/FloatingActionButtonSpeedDial#164]
Version 3.1.1 from October 2019 is still the latest released version. In the meantime there have been lots of fixes to this project. Will you release a newer version of the library or are changes from master still considered error-prone?

**Comment by leinardi** [comment]
Hi @fabiankr, if you check the [commit history](https://github.com/leinardi/FloatingActionButtonSpeedDial/commits/master) you'll notice that, beside the new features implemented by @S-H-Y-A, it is mostly dependencies updates.

I would prefer to wait a little before releasing a new update, I need to gather feedback to be sure that there are no regression.

If you want, you can help to speed up this process by trying to use the master branch and reporting here your experience. In case you are interested, check here please: https://github.com/leinardi/FloatingActionButtonSpeedDial#snapshots-development-branch

**Comment by fabiankr** [comment]
I noticed. I'm mainly interested in the dark theme adjustments. I'm already using the SNAPSHOT build and if I notice any issues I'll let you know. It'd just be nice to use the released version soon.

Thanks for the fast reply! :)

**Comment by leinardi** [comment]
Glad to hear that you are already using it! Please report back in 1-2 weeks and, if you'd have found no issue, I'll probably make a new release :)

**Comment by leinardi** [comment]
Release 3.2.0 available on Maven Central: ![Maven Central](https://img.shields.io/maven-central/v/com.leinardi.android/speed-dial)
