### ISSUE TITLE
FAB icons rotate only once

### ISSUE THREAD

**Issue by leinardi** [leinardi/FloatingActionButtonSpeedDial#4]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0-alpha02`
 - Android version: `all`
 - Support library version: `27.1.0`
 - Device brand: `Google`
 - Device model: `Emulator`

#### Steps to reproduce:

  1. Start the app
  2. Press the fab
  3. Repeat point 2

#### Observed Results:

  * The fab icons rotate only once
  

#### Expected Results:

  * The fab icons rotate every click

**Comment by jahirfiquitiva** [comment]
I think this still happens. At least on the sample app from Play Store, the main fab icon does not go back to the + icon, after closing the speed dial view

**Comment by leinardi** [comment]
Oh you are right, I forgot to update the Play Store app. I tested the latest master and it is fixed. I will update the Play Store asap.
