### ISSUE TITLE
Bug with hiding the FAB when scrolling a RecyclerView

### ISSUE THREAD

**Issue by KunaalKumar** [leinardi/FloatingActionButtonSpeedDial#40]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0-alpha04`
 - Android version: `8.1`
 - Device brand: `Google`
 - Device model: `Pixel 2 XL`

### Step 3: Describe the problem:
Fab stays hidden after recycler view has no items
#### Steps to reproduce:

  1. Scroll down in recycler view (fab gets hidden)
  2. Delete all items in recycler view
  3. Fab stays hidden

**Comment by KunaalKumar** [comment]
Hot fix that worked for me

```
// To check if view is scrollable
if (!(recyclerView.computeHorizontalScrollRange() > recyclerView.getWidth())) {
     speedDialView.show();
}
```

**Comment by leinardi** [comment]
Thanks for the bug report, I will look into it.

**Comment by leinardi** [comment]
Hi @KunaalKumar, I should have fixed this bug. If possible please try this snapshot and let me know if is working for you:

https://jitpack.io/#leinardi/FloatingActionButtonSpeedDial/feature~#40-recyclerview-bug-SNAPSHOT

This snapshot has some API changes, please have a look at the [changelog](https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/CHANGELOG.md).

**Comment by KunaalKumar** [comment]
Hey,

I think I'm missing something. 

Should I be checking if the view is scrollable(like in the hot fix above) in the onMainActionSelected and return true or false accordingly? 

Because that doesn't work as the onClickListener for the fab isn't called as i'm deleting views from the recyclerview.

**Comment by KunaalKumar** [comment]
On further review, looked like I was using the wrong version of the build.
If I'm not mistaken, I should be implementing the build from the branch called:

> feature~#40-recyclerview-bug

I can't seem to implement it into my buiid.gradle

**Comment by leinardi** [comment]
Mmm I am not sure I got it, were you able to get the snapshot to build? You need to add this to your gradle:

Add it in your root build.gradle at the end of repositories:

```
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

Add the dependency
`implementation 'com.github.leinardi:FloatingActionButtonSpeedDial:feature%7E#40-recyclerview-bug-SNAPSHOT' `

What I posted before was a link to the instructions, not the dependency itself.

**Comment by KunaalKumar** [comment]
Yep, did just that says 

> Failed to reslove: com.github

Not sure what I'm doing wrong. Using the master branch dependency works but not for the #40 branch

**Comment by leinardi** [comment]
In case the branch name is messing with jitpack.io, I have merged the PR on master, you can test with this snapshot:

`implementation 'com.github.leinardi:FloatingActionButtonSpeedDial:41ae2441b8'`

Please let me know if works or not.

**Comment by KunaalKumar** [comment]
That did it !

Bug's resolved, thanks !
