### ISSUE TITLE
Put some restrictions to the amount of FABs in SpeedDialView

### ISSUE THREAD

**Issue by jahirfiquitiva** [leinardi/FloatingActionButtonSpeedDial#46]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe the problem:

[Material Design](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions) guidelines mention:
"A floating action button should fling out at least three options."
"A floating action button should fling out no more than six options."

**Comment by leinardi** [comment]
Hey, thanks for your feedback, I agree, the guideline says that you **should** not have more than six, but does not says you _must_ not have it so, a restriction seems too much. In special cases can be useful and making the app crash it seems too much.

**Comment by jahirfiquitiva** [comment]
@leinardi 
You don't have to make the app crash. You can, for example, return a boolean with the method that adds the buttons, and if it exceeds the max count, simply return false.
The apps look really bad when having more than that and it's overcomplicating the use of the component, which implementation could probably fit in another kind of view.
