### ISSUE TITLE
error: cannot access AttachedBehavior

### ISSUE THREAD

**Issue by instantiator** [leinardi/FloatingActionButtonSpeedDial#49]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: com.leinardi.android:speed-dial:1.0-alpha05
 - Android version: 7.0
 - Support library version: 26.1.0
 - Device brand: Samsung
 - Device model: S6

#### Steps to reproduce:

  1. Add a `SpeedDialView` to your view as per the readme.
  2. Add a corresponding SpeedDialView member to your activity class.
  3. Attempt to compile.

#### Observed Results:

During compilation, you will receive the following message, which occurs at the first reference to the member in the activity class (after definition):

```
error: cannot access AttachedBehavior
class file for android.support.design.widget.CoordinatorLayout$AttachedBehavior not found
```

  

#### Expected Results:

I'd have expected the app to compile as normal. It's not clear to me what's missing or what's wrong.

So far I've found no reference to this particular error message or what might be causing it. I was previously not using a `CoordinatorLayout` but adding one (and ensuring that the `SpeedDialView` is a direct child of it) does not seem to have changed the compilation error (or gotten rid of it).

I have also tried with an without the `app:layout_behavior` parameter.

#### Relevant Code:

```
...

    <com.leinardi.android.speeddial.SpeedDialView
        android:id="@+id/fab_actions"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        app:srcCompat="@drawable/ic_add_white_24dp"
        app:layout_behavior="@string/speeddial_scrolling_view_snackbar_behavior"
        />

</android.support.design.widget.CoordinatorLayout>
```

and:

`@BindView(R.id.fab_actions) SpeedDialView fab_actions;` (I'm using ButterKnife to do the binding)
`fab_actions.setEnabled(view != null);` (this is where the error appears)

**Comment by leinardi** [comment]
Hey, I suspect is due to the version of the support library that you are using (`26.1.0`). Could you please try with the same version that the library is using (`27.1.1`)?

If it happens also with the new version of the library, could you please let me have a sample project where I can reproduce the issue?

**Comment by instantiator** [comment]
Thanks so much for the fast response! I was just coming to the same conclusion, and am currently downloading v27, and preparing to work against 27.1.1 for all the support libs. I'll update you ASAP.

**Comment by instantiator** [comment]
Hmm... I have upgraded to v27 and the 27.1.1 libraries. I also upgraded ButterKnife from 8.6.0 to 8.8.1 in case there was a problem there, too

 Unfortunately, I'm still seeing the exact same build issue.

I'm not sure why it refers me to the java source code. The source itself seems fine - but I guess it needs some kind of anchor point and in the absence of one in my code it must just be choosing the first reference to the member in the activity class.

```
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation "com.android.support:support-core-utils:27.1.1"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
```

I'll see if I can rustle together a project for you. Unfortunately it's all bound up in the project I'm working on which for commercial reasons I can't just share here.

**Comment by leinardi** [comment]
I'm sorry to hear that the library update did not help. Unfortunately without being able to reproduce I cannot do much. Maybe you could try to use this library sample code and try to replicate the issue there.

Let me know.

**Comment by instantiator** [comment]
Some additional information that may help:

- This problem does not seem to occur at alpha03.
- I've tested: alpha03, alpha04, alpha05.

For now I've rolled back to alpha03, as I don't think alpha05 helps me anyway. (I was hoping for an option to be able to control the truncation and/or font-size of the labels.)

I may not be able to produce a project today for you as I'm going to have to get back to my main tasks.

**Comment by leinardi** [comment]
Thanks for the additional info.

> I was hoping for an option to be able to control the truncation and/or font-size of the labels

You can control the width of the label and, consequently, where the text will be truncated, overriding the dimen `sd_label_max_width`: https://github.com/leinardi/FloatingActionButtonSpeedDial#how-can-i-change-the-maximum-length-of-the-label
You can change the label text size overriding the style `SpeedDial.FabLabelStyle`: https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/1fab81cfb5076ac9e7809296f6c2616544b06491/library/src/main/res/values/styles.xml#L34

Let me know if you manage to put a sample project together :)

**Comment by instantiator** [comment]
Thank you! It's a great project, and I'll whip you up something when I get some free time. Is there any way to support the project?

**Comment by instantiator** [comment]
I attempted to provide a new width for the labels, but it didn't seem to accept my new value:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="sd_label_max_width">240dp</dimen>
</resources>
```

(I created a new values xml file in the values resource folder.)

**Comment by leinardi** [comment]
Hi @instantiator, this was added in `alpha04` so, if you are using `alpha03`, it is expected to not work.

Regarding the way to support the project, you don't need to donate any money but I would appreciate any  kind of promotion of the library (starring the project on GitHub, suggesting Android newsletters or podcast to talk about the library, etc). 
Another thing you can do is to star [this issue](https://issuetracker.google.com/issues/77303906) that is currently blocking #10 and #11.
