### ISSUE TITLE
Menu Item visibility

### ISSUE THREAD

**Issue by bdushi** [leinardi/FloatingActionButtonSpeedDial#58]
How to manage Item visibility when I inflate from menu resources

**Comment by leinardi** [comment]
Hi @brddev, unfortunately the Menu Resource can be used only to add action items to the Speed Dial.

If you need to remove an item, you can use the `removeActionItemById()` method that takes as parameter the ID of the item defined in the Menu Resource: https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java#L141

The method returns a `SpeedDialActionItem` that you can keep and use later add it again via the `addActionItem()` method:
https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java#L123
