### ISSUE TITLE
Label transparent background

### ISSUE THREAD

**Issue by robertoestivill** [leinardi/FloatingActionButtonSpeedDial#60]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0.0`
 - Android version: `8.0.0`

#### Steps to reproduce:

The contrast between the label text color and the overlay color is enough for my use case, so I would like to have a completely transparent label background (or not background at all).

However, when I set `android.R.color.transparent` with `.setLabelBackgroundColor()` the default background seems to be set.

Also, because there's no access to the underlying `List<FabWithLabelView>` from `SpeedDialView` or `SpeedDialActionItem`, I can not perform further customizations.

#### Observed Results:

  * Action item label background IS NOT transparent
  

#### Expected Results:

  * Action item label background IS transparent

#### Relevant Code:

```kotlin
val colorTransparent = ContextCompat.getColor(this, android.R.color.transparent)
val colorWhite = ContextCompat.getColor(this, android.R.color.white)

val fabMenuAddCreditCard = SpeedDialActionItem.Builder(R.id.some_id,  R.drawable.some_drawable)
    .setLabel(getString(R.string.some_string))
    .setLabelColor(colorWhite)
    .setLabelBackgroundColor(colorTransparent)
    .create()
```

<img width="164" alt="screen shot 2018-06-07 at 12 29 52 pm" src="https://user-images.githubusercontent.com/3728545/41094421-8a5701ac-6a4e-11e8-9404-b18b541eede2.png">

When I used a slightly similar color 

`<color name="transparent2">#00000001</color>`

```kotlin
val colorTransparent = ContextCompat.getColor(this, R.color.transparent2)

val fabMenuAddCreditCard = SpeedDialActionItem.Builder(R.id.some_id,  R.drawable.some_drawable)
    .setLabel(getString(R.string.some_string))
    .setLabelColor(colorWhite)
    .setLabelBackgroundColor(colorTransparent)
    .create()
```

<img width="152" alt="screen shot 2018-06-07 at 12 35 36 pm" src="https://user-images.githubusercontent.com/3728545/41094661-5b7b9432-6a4f-11e8-9f0d-6e84135d318d.png">

**Comment by leinardi** [comment]
Hey I am really sorry for the delay: I read this issue when I was on vacation and I completely forgot about it.

I am going to try to fix it now. I will be back soon.

**Comment by leinardi** [comment]
I made a PR with the fix for the transparent label color. If you have time please try it and let me know if you can confirm the fixes.

**Comment by robertoestivill** [comment]
I have verified it works correctly with `1.0.1`. Thanks for the speedy fix.
