### ISSUE TITLE
Label getting trimmed for large texts

### ISSUE THREAD

**Issue by ashif-ismail** [leinardi/FloatingActionButtonSpeedDial#61]
it would be better to have an option to disable the trimming of characters if the label is large in length

**Comment by leinardi** [comment]
Hi @SheikhZayed,

you can control the width of the label and, consequently, where the text will be truncated, overriding the dimen `sd_label_max_width`: https://github.com/leinardi/FloatingActionButtonSpeedDial#how-can-i-change-the-maximum-length-of-the-label
