### ISSUE TITLE
Right to left locales

### ISSUE THREAD

**Issue by TomashVK** [leinardi/FloatingActionButtonSpeedDial#65]
When app/device locale is 'rtl' the SpeedDialActionItems are not centered. 
[<img width="322" alt="screen shot 2018-06-17 at 13 17 03" src="https://user-images.githubusercontent.com/40334228/41506959-d13edd30-7230-11e8-9ba4-71b4bb1d659b.png">](url)

**Comment by leinardi** [comment]
Hi @TomashVK, thank you for opening this issue. I have made a PR with a fix. If you can please try it and let me know if works also for you.

**Comment by TomashVK** [comment]
From some reason i cannot run the sample app.
Have any idea why?
If you can upload a new version i will be able to check it in my actual app - either way the fix looks good (code wise) in my opinion.

thanks.

**Comment by leinardi** [comment]
Are you getting an error at runtime or build time? Can you post the error here?

I merged the PR to master, can you please try the SNAPSHOT and confirm the fix?

https://jitpack.io/#leinardi/FloatingActionButtonSpeedDial/master-SNAPSHOT

**Comment by TomashVK** [comment]
The snapshot looks great and the bug is fixed
Regarding the sample app : 
<img width="867" alt="screen shot 2018-06-17 at 14 18 51" src="https://user-images.githubusercontent.com/40334228/41507350-bbd5f20e-7239-11e8-93a2-6d9fbe02de53.png">

**Comment by leinardi** [comment]
Thanks, this fix will be in the next release, meanwhile you can use the SNAPSHOT of master.

Regarting the sample project, can you please try to build from command line and post the error that is shown there?

`./gradlew clean build`

**Comment by TomashVK** [comment]
Toms-MBP-2:FloatingActionButtonSpeedDial-feature-65-rtl-margin-wrong tomvakrat$ ./gradlew clean buildStarting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/tomvakrat/Downloads/FloatingActionButtonSpeedDial-feature-65-rtl-margin-wrong/dependencies.gradle' line: 208

* What went wrong:
A problem occurred evaluating script.
> For input string: ""

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

**Comment by leinardi** [comment]
Oh I see, that bug happens when you remove the .git folder from the project (eg. if you download the project as zip directly from GitHub page instead of cloning it with git).

I will fix this on master, if you want fix it also on your side you can replace the line 208 of `dependencies.gradle` with this:

```
def commitCount = 'git rev-list --count HEAD'.execute().text.trim()
build_versions.version_code = commitCount ? commitCount as int : 0
```

**Comment by TomashVK** [comment]
Great.

Thanks for the fast response, and great library btw
