### ISSUE TITLE
How and where to add an Action Item in XML?

### ISSUE THREAD

**Issue by ShahoodulHassan** [leinardi/FloatingActionButtonSpeedDial#70]
Sorry if it is something obvious but I'm unable to figure out how to define an Action Item and where. And yeah, I don't want to define these in a menu resource if I end up losing the custom color functionality as mentioned in the docs.

**Comment by leinardi** [comment]
Hi @ShahoodulHassan, you loose the custom color functionality if you use the XML approach. If you do it programmatically you have access to all the features.

Please have a look at the [README](https://github.com/leinardi/FloatingActionButtonSpeedDial#customizing-the-items) file and at the [Sample App](https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java#L59).

**Comment by ShahoodulHassan** [comment]
Well my actual question was how to define the action items in XML. I found the answer in FAQ that we don't have to define them as a view or widget, these are just IDs defined in XML.

Thanks anyway!

**Comment by leinardi** [comment]
With XML I thought you were referring to the Resource Menu XML. It is not possible to define items inside a Layout XML.
