### ISSUE TITLE
Animation feels slower than Google Inbox

### ISSUE THREAD

**Issue by zhanghai** [leinardi/FloatingActionButtonSpeedDial#71]
### Step 1: Are you in the right place?

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library. (Sample app on Google Play)

### Step 2: Describe your environment

 - Library version: `1.0.1`
 - Android version: `8.1.0`
 - Support library version: Irrelavent
 - Device brand: Irrelavent
 - Device model: Irrelavent

#### Steps to reproduce:

1. Install sample app from Google Play and play with the speed dial view.
2. Install Google Inbox and play with the speed dial view.
3. Compare their animation speed.

#### Observed Results:

  * Animaiton feels noticeably slower than Inbox, in terms of both FAB appear duration and delay between them.
  

#### Expected Results:

  * Animaiton should have the same speed as Inbox.

#### Relevant Code:

The current duration is 200ms and the current delay is 50ms. Maybe it should be something lesser than that, but I haven't unpacked Google Inbox APK yet so I'm also unsure.

**Comment by leinardi** [comment]
Hi @DreaminginCodeZH, thank you for opening the issue. I pushed a fix, if you have time please have a look and let me know.

**Comment by zhanghai** [comment]
LGTM, thx!

**Comment by zhanghai** [comment]
And BTW, can I expect a release recently?

**Comment by leinardi** [comment]
I am planning to release soon, but I am not sure exactly when. Meanwhile, if you want, you can use the SNAPSHOT of the master branch: https://jitpack.io/#leinardi/FloatingActionButtonSpeedDial/master-SNAPSHOT

**Comment by leinardi** [comment]
@DreaminginCodeZH I just release v1.0.2.
