### ISSUE TITLE
FAB vertical padding should be 16dp instead of 18dp

### ISSUE THREAD

**Issue by zhanghai** [leinardi/FloatingActionButtonSpeedDial#72]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0.1`
 - Android version: `8.1.0`
 - Support library version: `27.1.1`
 - Device brand: `Irrelavent`
 - Device model: `Irrelavent`

#### Steps to reproduce:

1. Screenshot the sample app and compare the end and bottom spacing of the main FAB, which is 16dp v.s. 18dp.
2. Alternatively look at the shadow implementation of FAB, which calculates its padding to be horizontally the same as max elevation (i.e. 12dp when pressed), and vertically 1.5x of that (i.e. 18dp). I saw you were adding a 4dp right margin to compensate for the 12dp, however you didn't add a -2dp margin to both vertical sides. (Would also be great if you add 4dp for left so it's symmetric.)

#### Observed Results:

- Vetical spacing of main FAB is 18dp.
  

#### Expected Results:

- It should be 16dp.

**Comment by leinardi** [comment]
Hi @DreaminginCodeZH, I should have fixed the issue:
Before:
![image](https://user-images.githubusercontent.com/273338/41910526-364e23f0-794a-11e8-9f18-dc5a183cbbc5.png)
After:
![image](https://user-images.githubusercontent.com/273338/41910484-18d4d40e-794a-11e8-88ed-7928f3738e01.png)

I mistakenly merged it already to master, feel free to comment if you think is not fixed yet.
