### ISSUE TITLE
Highlight the selected mini fab icon

### ISSUE THREAD

**Issue by ashif-ismail** [leinardi/FloatingActionButtonSpeedDial#75]
when we have more mini fab within the parent fab,how do i highlight the currently selected fab ?

**Comment by leinardi** [comment]
Hi @SheikhZayed, what do you mean by "current selected"? Do you mean the selection when the user taps one without dismissing the Speed Dial?

**Comment by ashif-ismail** [comment]
yes,ofcourse 

my scenario : i add some esri map layers on click on mini fab,even after dismissing the speed dial if the map has the particular layer which has been added when the user clicked the mini fab for the first time.i need to highlight it .

any provision in the existing implementation ?

**Comment by leinardi** [comment]
Currently this feature is not implemented nor planned. My suggestion is to use the replace method to dynamically change the color of the selected action item.

If you check the sample project I am doing something similar with the Replace and Remove items:

https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java#L133

**Comment by ashif-ismail** [comment]
cool :) let me give a try 👍 .. any how thanks for your great library and continues effort in maintaining this 💯
