### ISSUE TITLE
Dynamic Theming of SpeedDialActionItem(s)

### ISSUE THREAD

**Issue by fennifith** [leinardi/FloatingActionButtonSpeedDial#80]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0.2`

#### Steps to reproduce:

  1. set up the library
  2. create a set of menus
  3. attempt to theme them dynamically

#### Observed Results:

  * after creating action items (through a Builder class), there is no way to change their colors/theme of SpeedDialActionItems without removing and re-creating all of the menu items individually, which is inefficient and annoying and dumb and I don't want to do it please provide some option other than this I really don't want to do this thanks
  

#### Expected Results:

  * methods to change attributes of individual FABs after they have been created would be very useful
  * my specific use case is a setting that changes the 'theme' of my application without restarting it
  * it also has a day/night theme that refreshes itself in onResume
  * I can see that the views are completely separated from the SpeedDialActionItem class, possibly to allow some sort of view recycling or some other organizational benefit, but if this change is made, then the Builder class will serve to do nothing but complicate implementation for no reason, and I would recommend removing it entirely and having users construct SpeedDialActionItems themselves.

#### Relevant Code:

There is quite a bit, but nothing especially useful.
Here is a link to [SpeedDialActionItem.java](https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/library/src/main/java/com/leinardi/android/speeddial/SpeedDialActionItem.java) if it makes your life easier.

I am currently using Jahir's abandoned [FABsMenu](https://github.com/jahirfiquitiva/FABsMenu) library, so there is not a huge amount of urgency for this to be completed at the moment, but I would like to migrate to this one before the lack of support becomes an issue. If I have the time, I may simply fix this myself and create a PR, but that will likely not happen for another week or two.

Thank you for creating and maintaining this project. Apart from this one issue it is very nice, has a lot more functionality than one would expect from a row of buttons (option for inflating a menu resource is good), and the animations are completely flawless.

**Comment by leinardi** [comment]
Hi @TheAndroidMaster, thank you for your suggestion, I am not sure how complex it will be to implement what you are asking, I will give it a try this weekend.

I will let you know.

**Comment by leinardi** [comment]
Hi @TheAndroidMaster, I spent a couple of hours evaluating the pro and cons of doing what you asked but in the end I still prefer to have the separation between the `SpeedDialActionItem` and the `FabWithLabelView`. This implies that if someone want to change the theme of all the items it has to either relay on the theme functionality provided by the framework (which imply the recreation of the Activity) or updating manually every Action Item.
To make this manual update a little more easy I made some changes to the `SpeedDialActionItem` and `FabWithLabelView`.

It is now possible to change only a specific value of an Action Item without having to set back manually all the other values:

```
Drawable drawable = AppCompatResources.getDrawable(MainActivity.this, R.drawable.ic_custom_color);
FabWithLabelView fabWithLabelView = mSpeedDialView.addActionItem(new SpeedDialActionItem.Builder(R.id
        .fab_custom_color, drawable)
        .setFabImageTintColor(ResourcesCompat.getColor(getResources(), R.color.inbox_primary, getTheme()))
        .setLabel(R.string.label_custom_color)
        .setLabelColor(Color.WHITE)
        .setLabelBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.inbox_primary,
                getTheme()))
        .create());

// I can change dynamically just the background color
if (fabWithLabelView != null) {
    fabWithLabelView.setSpeedDialActionItem(fabWithLabelView.getSpeedDialActionItemBuilder()
            .setFabBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.material_white_1000,
                    getTheme()))
            .create());
}
```

I know that is still convoluted but I hope you will agree that is at least an improvement. You can find all the changes in #82

**Comment by fennifith** [comment]
@leinardi that was basically what I was expecting, thank you very much!

My other suggestion was not to join the item and view, but to eliminate the 'Builder' subclass in order to simplify the API and instead allow the creation of menu items like:

```
new SpeedDialActionItem() //creates item with blank label and default colors, blank icon, etc
    .setLabel(R.string.something)
    .setFabBackgroundColor(Color.BLUE)
```

...and then you could simply call `item.setLabel(R.string.somethingelse);` to change one of the values.

Apologies if this is too complicated of a change, perhaps this should be moved into a separate issue. Either way, #82 solves my problem. Thanks again!
