### ISSUE TITLE
set scale scale of mini fab icons 

### ISSUE THREAD

**Issue by ashif-ismail** [leinardi/FloatingActionButtonSpeedDial#83]
is there a way to set the scale type for mini fab icons ?

**Comment by leinardi** [comment]
Hi @SheikhZayed, if is possible to do it with a normal `FloatingActionButton`, it should not be too difficult to implement.

Can you please give me some example of code and some screenshots of what you want achieve with a `FloatingActionButton`?

**Comment by ashif-ismail** [comment]
i'm trying to set a custom icon which has a round border with it to the mini fabs..no matter whatever size of the image i put.. its always getting center scaled .

what i want is .. the round border of the image should be exactly at the outer bounds of the mini fab 

check this.. i want the icons of mini fab to be strethed out fully 

![screenshot_20180730-121118](https://user-images.githubusercontent.com/8774293/43385468-e0639980-93f1-11e8-8ed4-24a19ebcaf61.png)

**Comment by leinardi** [comment]
As far as I know this is not possible with the `android.support.design.widget.FloatingActionButton`.

**Comment by ashif-ismail** [comment]
cool..thanks for the info
