### ISSUE TITLE
Sample Project NOT building

### ISSUE THREAD

**Issue by RedSkyRoad** [leinardi/FloatingActionButtonSpeedDial#87]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: 1.0.2
 - Android version: 8
 - Support library version: `?`
 - Device brand: `?`
 - Device model: `?`

#### Steps to reproduce:

  1. I've downloaded the full download and the "sample project" but neither build.  With the Sample project I get the following message : Plugin with id 'com.android.application' not found.

**Comment by leinardi** [comment]
Hi @RedSkyRoad, I cannot reproduce this issue. I downloaded a fresh copy of the repository and everything build correctly, including the sample project.

Please can you try to follow these exact steps an let me know if you still have the same issue?

```
git clone https://github.com/leinardi/FloatingActionButtonSpeedDial.git
cd FloatingActionButtonSpeedDial
./gradlew sample:build
```

Also please be sure to update your Android SDK to the latest version.

**Comment by RedSkyRoad** [comment]
Hi,

I'm not an android pro so I need some help with getting this to work. What are the steps to get the sample running? All my SDKs are up to date. Do extract the whole folder or just the same folder? Do I need to copy some files from the other folders as well?

**Comment by leinardi** [comment]
Hi @RedSkyRoad, the steps to get it to work are the one I listed in my previous comment, assuming that you are using the latest version of the Android SDK.

If you want to open it in Android Studio (better to use version 3.2) you have to just clone the project with `git clone https://github.com/leinardi/FloatingActionButtonSpeedDial.git` or download the Zip archive from GitHub:
![image](https://user-images.githubusercontent.com/273338/45203795-8f526d00-b27d-11e8-82e1-7d15e45dc71f.png)

An then just open the root folder of the project (not the sample folder) in Android Studio:
![image](https://user-images.githubusercontent.com/273338/45203854-c32d9280-b27d-11e8-83eb-08229b3e5e0a.png).

**Comment by RedSkyRoad** [comment]
I've done that but it does not work... I get so many errors. I'm running the latest Studio and SDKS

**Comment by leinardi** [comment]
Can you post here the errors are you getting in Android Studio?

**Comment by RedSkyRoad** [comment]
Just at work atm... Will post results soon.
Just tell me : will it be possible to have all the code in my app so I'm not bound by dependencies?

**Comment by leinardi** [comment]
> will it be possible to have all the code in my app so I'm not bound by dependencies
If by dependencies you mean just this library and not also the transient dependencies, yes it should be possible. But why you don't want to add it as dependency?

**Comment by RedSkyRoad** [comment]
If this library would make it possible to set up an awesome FAB in 10 minutes, then I'll be dependent. 
How do I do that? Stepwise... 

I've spent 2 days now trying one after the other with ZERO success. 

But I see a lot of Deprecated libraries... I would like to find something that works and stick with it without it being fiddled with in the background...

**Comment by RedSkyRoad** [comment]
So I cloned it and here are the errors.  After clicking UPDATE, the rest of the errors proceed:

![error01](https://user-images.githubusercontent.com/8761621/45251825-0440a800-b34d-11e8-9f99-f132d0bd4083.png)
![error02](https://user-images.githubusercontent.com/8761621/45251827-0e62a680-b34d-11e8-923a-359df1c3a771.png)
![error03](https://user-images.githubusercontent.com/8761621/45251829-13275a80-b34d-11e8-8e69-5b6f47dd9f98.png)

What should I do?  I'm trying to use this sample so I can see how and where to put all the code I need in my project.  From the instructions I'm not sure...

**Comment by leinardi** [comment]
Try to change this line to `3.2.0-rc02` and try again:

https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/07d61e40a0f7e87a51893db093be09423b01893c/dependencies.gradle#L24

**Comment by RedSkyRoad** [comment]
Thanks SO MUCH.  That helped with the first errors.  I still have the following:

![image](https://user-images.githubusercontent.com/8761621/45252313-94362000-b354-11e8-82a3-bddac14d5a06.png)

**Comment by RedSkyRoad** [comment]
PS: When I try and follow the instructions on the main page, there is something called "fab_link" that is in red.  Where do I get this file/reference?

![image](https://user-images.githubusercontent.com/8761621/45252337-e8d99b00-b354-11e8-9809-92ec87ad324a.png)

**Comment by RedSkyRoad** [comment]
More Errors:

![image](https://user-images.githubusercontent.com/8761621/45252501-b2514f80-b357-11e8-9890-e0aeaa840eac.png)

It just does NOT want to build

**Comment by RedSkyRoad** [comment]
So the source of that error is the following:
![image](https://user-images.githubusercontent.com/8761621/45261095-a74efb80-b3f9-11e8-8bbc-86ace23c6822.png)

Could someone please tell me how to fix this?
