### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by marbat87** [leinardi/FloatingActionButtonSpeedDial#92]
Hi,

androidx support lirabries are out and stable.
Any ETA for upgrading?

Thanks in advance

**Comment by leinardi** [comment]
Hi @marbat87, currently I have no ETA for it because I need first to understand how can I still support the projects that use the old support library without having to handle both dependencies on my side.

As far as I know you should be able to use this library with AndroidX setting the following two flags to `true` in your `gradle.properties` file:

```
android.useAndroidX=true
android.enableJetifier=true
```
More info here: https://developer.android.com/topic/libraries/support-library/refactor#migrate

**Comment by marbat87** [comment]
You should support only the AndroidX, because the older support libraries won't be updated anymore.
However I will try with that workaround in the meantime.

Thanks

**Comment by hannesa2** [comment]
Adding simply

> android.useAndroidX=true
> android.enableJetifier=true
> 

is to less, you will run into tons of errors

> Task :library:compileDebugJavaWithJavac
~/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialView.java:28: error: package android.support.annotation does not exist
import android.support.annotation.ColorInt;
                                 ^
~/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialView.java:29: error: package android.support.annotation does not exist
import android.support.annotation.DrawableRes;
                                 ^
~/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialView.java:30: error: package android.support.annotation does not exist
import android.support.annotation.IdRes;
                                 ^
~/FloatingActionButtonSpeedDial/library/src/main/java/com/leinardi/android/speeddial/SpeedDialView.java:31: error: package android.support.annotation does not exist
import android.support.annotation.IntDef;
                                 ^

**Comment by hannesa2** [comment]
please see `AndroidX` PR https://github.com/leinardi/FloatingActionButtonSpeedDial/pull/103

**Comment by leinardi** [comment]
> Adding simply
> 
> android.useAndroidX=true
> android.enableJetifier=true
> 
> is to less, you will run into tons of errors

Hi Hannes, if I get it right you are trying to build the source of this library adding the `useAndroidX` and `enableJetifier` parameters and that is the problem: you should use those parameters in the project where you are using FloatingActionButtonSpeedDial library and not to build directly the source of the library.

If you do it like that it works fine and you don't get any error.

So there is no need to move this library to androidx yet, but thanks for the PR.

**Comment by leinardi** [comment]
Released fix: https://github.com/leinardi/FloatingActionButtonSpeedDial/releases/tag/3.0.0
