### ISSUE TITLE
Is possible to change the backgroundColor of a speedDialActionItem programmatically??

### ISSUE THREAD

**Issue by migvf** [leinardi/FloatingActionButtonSpeedDial#97]
Hello,

I need to change the color or the fab icon when the user clicks a menu action (to show which option is currently selected) . Is this supported? How can i do that?.

Regards

**Comment by leinardi** [comment]
Hi,

unfortunately this feature is not supported, you can find more info here: https://github.com/leinardi/FloatingActionButtonSpeedDial/issues/75#issuecomment-403775804
